import: definition.yaml

concurrency:
  task:
    alfworld-env_train: 16
    alfworld-std: 16
  agent:
    qwen3-4b-instruct: 16

assignments:
  - agent:
      - qwen3-4b-instruct
    task:
      # - alfworld-std
      - alfworld-env_train

output: "outputs/{TIMESTAMP}"
