import: definition.yaml

concurrency:
  task:
    alfworld-env_train: 16
    alfworld-std: 32
  agent:
    qwen3-4b-instruct: 32

assignments:
  - agent:
      - qwen3-4b-instruct
    task:
      - alfworld-std
      # - alfworld-env_train

output: "outputs/alfworld/{TIMESTAMP}-no-h5"

trials: 1