import: definition.yaml

concurrency:
  task:
    webshop-env_train: 32
    webshop-std: 32
  agent:
    qwen3-4b-instruct: 32

assignments:
  - agent:
      - qwen3-4b-instruct
    task:
      # - webshop-env_train
      - webshop-std

output: "outputs/webshop/{TIMESTAMP}-test-harness"
trials: 1